# cd /etc/nginx/conf.d/
# ls -l
# total 4
# -rwxr-xr-x 1 root root 1692 Aug  4 14:19 default.conf
# cat default.conf

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name localhost;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name localhost;
    root /usr/share/nginx/html;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    location / {
        try_files $uri $uri/ /index.html;
        index index.html index.htm;
    }
    # Opcional: Configuración para mejorar la seguridad
    location ~ /\.ht {
        deny all;
    }

    location /static/ {
        root /usr/share/nginx/html;
    }
}
